#include <iostream>

using namespace std;


void recursiveReverse(string &str, int i = 0)
{
    int n = str.length();
    if (i == n / 2)
        return;
    swap(str[i], str[n - i - 1]);
    recursiveReverse(str, i + 1);
}


/*bool palindrome(string A, int start, int end)
{
    if (start == end)
    return true;
 
    
    if (A[start] != A[end])
    return false;
 
    if (start < end + 1)
    return palindrome(A, start + 1, end - 1);
 
    return true;
}*/


int solve(string A) {
    
    int start =0;
    int end =A.size();
    string B=A;
    recursiveReverse(A, 0);
    
    if(A== B)
     return 1;
    else return 0;
    
    
} 

int main()
{
    string S="kmwcgtpmzsuwvtzdnpdlxzgwgaewksrmrtkohnnldgnnunteezkgyexxcwcuznuuukygmxcacupthnwsezponuzsmuteqdpagwoxylfdhmpcixmpevrgxmiogufdwihydthbsypkofpiwendztwxrumwuyeotposasxlyekqkhogouikpfoemjurvfsgoccepiobtuufpfestybtmlfawczmthroigljoldnoglauipfjgwitdtgnlhukbplabcnzokcnfsoaiqkemkbndsxtqqenweiapvsdxthuiubxvrfoyaufcspebcxxdugieaccwtmwdpzqvsmtaquhcbbmoklqdldjlosoqsdopdouwqvxxstftnkamorzihkmganadspkgognejmbxjcxjiddncvynekuoosbnwipysowhfgqdhxjoblernbejcaxxgixamtioeiqshvzxkjxotinxyoacubjukrxsvnmcbdvffsoiyrgnyzxnjhmptmgzyvocdtfkvxhoujlequtswoikugzqpeyiqpwduovmkcldgmlfzrdmcspdiuebizxekntrxfgklhuihwzwnjabwjtmfzugjczoucgpknqvcltlgsglyzhkggoqlinsadowyryrwgrrdyeejghparvjycljktvrvwebwfobdhgfpankwaqawgwmnaemxtbyywylxvrtpuabuiabudlzwjanyngpxjkjsktoyxjxzngsxwuioxxqqpoazpcmkpejewsinygmnrgaezbmvvvhrzlisbwbouqaqebpsmvmllqdfmhvkalsmgnnvabsfutkgxyfemzeenddvuvrejytnfpofdexqctwulyghgxemtavemczodunszmybxrazitzhtywvdvbzaanodkenhskifztvtdmqryvkpmuzgrryatgycpgiollhvolxqjvowkxknnivttengzbnjsyfsrkhctcxtpvkgbvironztntdxuuozwuympeudlssdrqaqabbpysswbjeycdhuucxvwlprtaeugqedgvoivmoteyoqbgcirsjerllfqojndvxawnkdpiokzbeslbpkxypqslszwrybhhfnvzmnngwozuefgritimluffowupezyqgppxgworqiojpjqnqzbgzlfqxefphesvqhmrutrcnnievxidruzzxyrecqtbbhfcyajirhejpkajsvnwhjxtcgfqgiypozjqrpfupnuvspxovbgkeeznwvgayjnysrwkafoiyktobjcfogjtrsbmxibcjypetuicwtdhnsgyjcworvixiidkassmsqgqpgrgqftbakmplphabgimrpflcsooksbcgmzhvguibuxwaabjahwatyjsnbqfigrfmxywgwflvhopnerpyplurkauryajffaxvaulyzjpdpvtzskmiangzefncwlfdtxuoazrrqwwbpdxdgkiupsfhutmsdprqkvuspwuxulrpkflqcutpzooilijvqrehzybdywupqiqzadgmbhjzrfpymdibmaoovnejdqxuhcvsiklbxrdakzmremjeqcnvnrvtpyzzjomqstbhvcvtdceeaaygrawtwagtweoqzyprfyljsjiwrkqztshpiyfywbsvjdvtyniejebknzuwuxgmowulyzxwrstrtouuclabxouexjszrepsqvastqzqxyywxfgntbzjegyhpclxewfjqnxvckpxryszqhqqmweizkljaybrtoipwtolhtstjivwovojspiulxvdbdnfngkpbcaxxxpgrbsxejkxdinunoqnoexltozkqaflisrazjdkzscbnfdukysjcatctnlcsmlnvibrkztqwrgftuexeodcitcytconohqwhjhgccgubctjbjifcqbehcspgibhjbiwuakqiuoqswdssywirsnucmpiqfgtmrctfwudsahgrmfmbwavqtfqexbhkdmthcascukbfdrgeudblmkwyqvkcyuxbmslveyxekanglgdyssujdtfkphhkoboggewxxgzjyvdobenhdyzzlbdlhhethzegpucagkaebedqgiaaypecorahhhnuwyiufagleamqifqjmsbnkauivmqtxpbgmrmfuuitgegauduikuoubdhazkmguazqfszdwvizxccdiumfugapqxgwbgxzfjgjptxxuxrezezjyjehteoqghbpvqzdecqkdqunluzdqfxpiwwbicrohdssjpwbrigqarvhwmdatlazdcdypkneaymsnzuitbkctrmmfzhidkvxskhvlqkvthpexelbtrsemctxqzfksokwtvkxmawvvxckvovhafrpvtpqqaevhrjlhyfvblyxfnnjzvaqondwakqdskwannqoalcglbzuppawfiudwysmwuyjthtaematbfzhgyqbzmyyhornfsmkrpyovqqayhaftchipgtncmblupjhbawxhvajhlwoaeyxehgorrlwppnzvovqninssvjdoxvdkfcdlidwyheppbxuztidpebxnsxjgvruowrerqavjkeolurmawuteyyxkgsugoimydnmpirmjjcsfavepdnohczovenrcbcijmaxrkjvgscjhxaycginkyoegcinkcstxvvfrhkzvlqwmpexhblmropgwsycdolydwormpfasisgfwiyyuuyxxzpugzpxtfcmdjvnjafezxspncqayvnqpovxatwwwkxnrrmylbmcmebaeiqbzhtgossperquvmgyexgqcbkkrhxahjpbjvqrimdwqrvglixlisqcpuatoadlujyxelxktkivmpppwaqmlfbmjetrardzzdmqcpszjkuthghbxwgpdrujxespfvhodttuvtuhynycrklkokiaalkyrglayjirlnocbyknoebfmhyigikjgwwlcetkubvvvqxcbdsgarqfqwcczhdcufxlwpqyrhqfcaezihoaggcuxhmuukfxaazmrfmlnjpjsziwglbdasidvzwufojzmtlfulolfuvvlqwpouwnwnopcaidgtljeufvqetlmuqwjxglmzxaehtixqsobtgogkxiaddaqbljwijfuxmakaxlmsudorbyaedhnygqqqifgiddydulwnmtokpgwnljoqvirebhilzjfbnmzdvfjavsdtrccplikeeeiiwmarlbsshlzhwsbtxeevtbcsligedszoaecdffpbcgnosfrmeyounnnkodhnbrqwxgeovoekvwkostbbgpvneslyosbvsrdvlryobpnainsbdzwtmgeuwjwekubmtkclzzwrasovugwwlxmvyllrnjcuazopdqpsoordygrnvozrzxymjksbpcbdjmntppodchbjquaxevqkhscenbegrfsfmwtiwlzaffqalsioxiwywrhpswtipbncdpqavnthaokjgswubkzksxbsunpkyybrlcpbpgktzlhqgdkjfjogsahdjeymtrnygcejwjmxxtnyltfdwxlczgdiwdwlqmxxfrsgdyllrgybamxizrgwfztiiiwxvgttohdqftlrepdplmsrncjrxxnpplfgaojribkhtxovvflvtcmhpvaldwhgcglfvyvtyeqrqfmjpamxeuuspzxsqzardpdctjurdrbapuzzpovhtzsqqeefgtbmqhrcdjntulsrzsznruirxkbthotuapcwyvxdbzqdvodthgnkqnnqtoxotwdorjkjcrnnmskflgjcjldptmwludritncrioxrgshrgyzxisuikxdvzufgarzloplbcrdvvdonxgfkfdjmybhojvptgaxzhhhrygysbcypzrghwhfuddfiydkiowzwkygtblwgyesislwbcfkawzpuflhmivfhsumqnnzvrfoevrdouikpierjhyberamtdoempzcftezjsqmroyqxzimymsmcciytzvrnmbxidgvocsnwhgaminkazsisdgdcnhxinsllcjqfegxvbwpfhdtkehzgiiupohltbvtzkuxbkqrfhbzgfrfvltnhudlpuntwnytuhmxowhzydkvgkmceffhrlvezjibiacdmczygsglusfhxrtykhynuclpsotldmmrbvsfakfgpzdhtbmjhpsozdktwhwtbacbynlmazrvyvtqhvpvzifgwgkixvspzaxssrbrhyrcerbuzudokmgoyeaobwzewuouzcrufdrslxbecajjfcmgssmchowiujrlfrlrilldhovgiahyyycoxkvscyampozaesgqvmmbamfjvqgljlbflsqkqzinnxkrtmoteifurztfcypmdmhhwjxefnsbomackjiybzvatwjkvbivzgcvurpyvemycsxnlerqtflhowdgsywsluthgrbshzzkdvapvboxexxxkqtrzcodjshoxmhqnamfootylvldupjktrjotoczutgispirvaawkiwmldikiwczdjxbnsheeslvxfnnqedtmyckfplietfklghjholersbhxzwubbiqcxeetwaxneqvezmyjrlvpzoyemdcmgmddewqhszjztgikujfgnyxhnxzqejjnlbanahwzyjjyuyzlshoejuwggfuoahlzhrdymwqjkjjdxycwmujlusckwsxmhawcovwdqbrrzawwzfbxfyhuowpteypmkgcetcrkfbobqgkirqvqcqilpbbjqgcgsdyzcbwhtpbniucljvisjhrgwuvblbhtaduyuyvywnbseezfsscfpdiqjobfvcpefyrawrfkbzefqgdroijodzuqdlttmeebncippyysdwyolgnllgzjakxzhtjwzzjcvlblcnouarfvnhnbfvsyqmvlqxdtftizfjmufermfhvrdhbquasspyiwtonuenspbuonrvlgufguzcmyxvrnrvesndzrkevvcwcuvcjdtrpqarofyyjzmvupzggxeuylnjkrwrmlffwkbfpkqkdlzlbmumsukyuvoxpvvfsshmumvqhjmoplfidfcsjabbupbzdntjykezcwhfydqcatyqfqgwxbgjfideuhlwabviilhxneeltuxuhbwwgsabnekjixiauyemmlmgvigipfagnderiagzpfzcltrfayfauxnywoidtyvunddgbbbslughllcwwibguhdybythlfiqjnkohzmlpvpxbveaqomvjldxyfsxckcdqttneslkhnbnvnqknarrhsiuflbbtxxfqdovfxpgrrljidxdjhvniuzqsuzngqwywqkeujlmpshefvcfxbxqqfzbtvumopvzjmdnjjskvwtdwbkeksoknmjllqgjjuzjltswoshzdjwyftcbklombavnihyrzdpkuwcpvpbufvygijtbvwopoqmqlrlfbmipqvassvzlepssradwnzmticlnqcnvtwffpnxqxxlrwipihxfkypdahspwgibriazsylolpguatrcdwrdcpxfezyfljchiygvdscwdsgcxxwcmbctwezfwreospujpmkpyxklesvqpkqwjwsgkclyolbjzzpcaqhmwejepdfoeqdjogspabpbinxseidlggjmatpextllhppjubouvuwdzpeigaubkqwreoukuisiqqrncnqeuluyxvimemhhcomanbulvgopixvcpfvnzdzthwarpqyphzysuwnsznrhaunlzvmqvgcvwjpwbgqremdxvsgwwnlocbdzlwrtjlbnwkykauxebtrdcbmcffthtqofidotrmpwawesbqlowhyjngbvovekypjgmgthwqojxrsvpgzoyichnupjkhumvmkcsqotivwlithqxoltosioiflfodbyfptgcyuuyzublosrcyjgbxzzchvmyfnvnnacfdygjiokmqyvcjemsrvjmextbhwgnsmkmkcivsxgalrdtbajfvsxwysxcfltkzixltwolppmokbgsglqohgejaiazsdngpscghlfsdozrxhzcmkzemcfizpzgmofimqeeolaktjcxzjbpxtkiluanzciwnscbwkuiseyllewgrjbkzfouimylvzubfsozqfordbmyrtigfcpwewgpnfvlfnzjumdgfzmkxslwrbzdpwwdxgpemjpshesmeqxnficbuzsqvcbxkqypmiefvtryjsazzxsghjjokzfxhszwdgxfywnvybubdseerdfzpiawtwpdtinyaomihfgdbfgufozavgsqlacoldfqzrhlengnmvuvxktayxnwvxeexjkplgmhqdikbxbnredmomuocdzqmxbuxpenfnfjiwdmtddypdmkasvgaavlxufcddecrvxcyueqixfwweyozgtgdbuwawjalnnohevfxxpgudryvruhlwnozquzhfoqewdnfnzvyxvalywhmvhvqvseqlgnhoibiatbekysymsrzgjnkadrmdlwxaflhpjbphcdnrmdbvjogzzvdghzgytjjexfxgcexgtmkrltmrutpnzmfahysbvkostwaihfonfbceoeuvhrcriiuqplbvvkjatvmjbbuvtgfqmnpxobqatkazsacziluammtyrulqidbabicmpskgqfsjponyrajykhzvssswktekrmbuzqcdkldufyurddcfujoufyamynumrmsfdrevhrnrhconntbyfvgclmfqnwbfnojmkqzhegbafhunovedcubbpsiuonvxqhxxqqxojkditkeydrnscsskdstycgfxgnwiguvuefznwbhalqhvtdtboxmbqdpdrhjppqvfhqxpaxjvliupundglsfihjtlksibuzcvxabhgeyvvoluwidalnmhtjpoynulihwjukrnvpefofhqmupvxmaidhxghenrvfzjvmgvojxtvbgasdbhwlntxqftflxpkupbhgoqugftblqtglqhnbavknnqhnhznixecwqcvnemvmcrwstjiyobumaajvgwlaxdcprtkwwlamraqmwpwurpvjfjkgogskagxhngxaqmzqllfxayjotdtbqhlearrlqtjgsbgycpkxbutzfuohwzvcuudoyqramujabpetgtivlfpxlwvpkibqbyhvkwmjklcqxyutqygsxsbiamfgksthnqtpslvluipyuincewznpgzumwpxjvdyodayefyfvfmyzaqlaamfduaitdnzbkmnxnapstspsueyocrhccibhunvjtenzrupcqchyfnqzruptzorliwtpaoznzgyjvhlmhytqhwfduveyjcjnpvyumvbpfcgjshshghrchqsywwcpcxwsbipydhtkvehvqjyufqfjcmtusvpslwpbkfcknckbcfuoyjvtjmvhprblardbucsghrmpkfjeyuwggarcsknowihximrenwzzhhjtfpynldyyhocoysfgpmeevsiexbhcykgogzgjsuwcpcueubhjkbbwbcadgdlwqbcfkuyhtoszcjkufwxgmuqxyhqdyzpndzrhoncpetkfdorboonuykrgnsdecdigyjjyvrkukeqkoogpmqsjgkxrawzystvntjzlvojcyqauuyvugrpkahttphptjahlwoocwbizessxrjndlgtfwiphhluvznwvepplgzufczoytpyrkageyuyawdovyxgzxdvmrpugwukzzphvykknrlnrdxwnzfhrapkhhmuuamnwxynepmkycguamojucfnwickesbgxpekoxtmmjrvxfcysndpuuzywkdclfzjoysspbjxpiyotwssalpaizclocpnaptgjjfxwghgopuemwlqqujfkrcbgmeigsejhspzmtiqtdoxbrumlonpfxizlkbdnowhhsynxsuewqxtvfenzmolhrjxhlsadcavlnmeenwifoyhgdoomtivrlstqwftcgjdjrzvtwyzmtcmahdmksulzisypuboseemmvgmzybgvepgvkztggqtgmrbebdhffabxkctmqtzohyzzybkayvzedinmyjyvloskhusfcsjwelyvveefrejdorynnihtcdkaiqffawoxcufnybbeadpdpksqwksljxalxfsxaendsiqadjgnunluhehbgkstkxmzwqvohqjqoeteenbqlyhlucxchkijwcayjqyabekwswleiqtbhjbngzkptpbtdhhocstcajdnfffkzipkimrkyswuuohnbnobltrwfffxtdhlfinnhildinzmzogdvbmzeijcojusurgnxsnqlssylifctyjtnszfzdimoyoxynzlslgwcddfbgzemmnlvotlvdmktsdiessvszkziuikqhcjufcsiuuevlbclojoxtccjsntxqsnbyrjpzluxoavwecqhyawrehapubocbyimaegqjhnkfxaofcmxziycesrucrcziakfcbgchojvbtfqbcqkfpaobwdgqkjgpjtxdfrgstcwdozylyfgtfdmwdkjgwzushomdllrbvelwkxszstlaeiwzumqwxwpmzealgdysgzzutzpssayncjovehmzxziwkzinunomtwzinabcoupdbxthxmaiecedazsfruknblluogyqydfduwwejngwwdcigvbatthmgcjvxvgyqtouqwpnfakatmixfarfecrzmhhdbvyouyggangfwthinzipzqglyzurwkybasfkilwmyzqbzosmsiaptsntpjzznvdejwzzdcyjwuzlzvbxuhhmfomxrfsageenlrozcfoaxdpmeayllvefioqhmflhwvrlmusougcuuswtstxdxpetloxwpqnanimexdyxjndehqhdqvuazxnneozujaqmbiqbwroyfayrpivztkyxeieygafkjxfzzphcqjoqnrzptknytgkxzchfzgfrflyywtzfyztiymitpyatnlciybywmyfsxmjvmmhjalambgzxiergkjoznseuibyguupkekspdwtlenvkjstoysgyjvhakdofntodrtaskzydputcylppgudwhvlfgupivuulrbvdtqetsgfsopcrnghpomvmueszyfqeipumkmzhbnxxkpubdxwmivvyivjdirqszttfqfliknvnizjwldbehetmqnrwjvqeetmmadirtdupoegwljfnrnesmaavjxhanobcvovrkcatjgqdwvmdikavblqhmdibytthichxlaxwyyoijxibivggkuckcjzgmnvllxcmpomqgwizalstxgkassobxlcmzzuemxctfgzilrkbgmsorpygjfrwtedmgjrfuhniciplgjcgbsctqzxlaqxyrymqmrfqqlkowyebevikquudlezezdshefhrucjssmfetyatfpqwgljtlysagjrsrzalaoypjfurccehapkxvdaezrpapsosigpwkmlgohcgkewcnfjtspnnjbkohtboxiqvevgyjjeckffclzuqcyovhkvzcoddzvhrsgjmvdgogpbkjpxzrdbioadeaianrrhtuorfpdmxkxitrfoekdfvlvxiwzerwkbweljilbhycgjijukyqyfhkuxaprstapvcuqgiusblitayeafehvtherxftyyokyfzobqfryancbkqlfvjmqvqmseyrolsdzgudbteehuteizzxpvempjhcrszeadincuvsohhjvasudrtpuhhjmfddspbihsnstbtqdgqdqxlkdlpxihztnciavbshnzptetrdheivmjqrytcpjssvallfmrgwzwzbvprxohgqckacftrubgronwsnqnmojgbahufxzwyqskbgatjffgktyxhlhjxuxrmwmqyemkyrrwarrkzqfqcakzrtatlvxncnpfcgzlbzqltrwpagcocptqxavtgjvdwzgpaijxpgbopvvutuhtbwscpqfcvkznlngjjhuvru...";
    
    if(solve(S) == 1)
        cout <<"palindrem";
    else
    cout <<"palindrem";
   
   
   return 0;
}
